fix syntax errors in if statements

diff --git a/.github/workflows/build_docker_container.yaml b/.github/workflows/build_docker_container.yaml
--- a/.github/workflows/build_docker_container.yaml
+++ b/.github/workflows/build_docker_container.yaml
@@ -101,15 +101,17 @@ jobs:
           export foo=$(docker manifest inspect ${{ env.REGISTRY }}/${{ env.DOCKER_METADATA_OUTPUT_TAGS }})
       
           if [[ $foo == "" ]]; then
+            echo "tag is missing, need to generate"
             echo "tag_missing=true" >> $GITHUB_OUTPUT
           else
+            echo "tag is present, no need to generate (unless FORCE_PUSH_IMAGE is set)"
             echo "tag_missing=false" >> $GITHUB_OUTPUT
           fi
         shell: bash
 
       - name: Extract metadata (tags, labels) for Docker
         id: meta
-        if: (steps.check_tag.outputs.tag_missing == 'true' && inputs.PUSH_IMAGE) || (inputs.FORCE_PUSH_IMAGE)
+        if: (${{ steps.check_tag.outputs.tag_missing == 'true' && inputs.PUSH_IMAGE }}) || (${{ inputs.FORCE_PUSH_IMAGE }})
         uses: docker/metadata-action@v5
         with:
           images: |
@@ -124,7 +126,7 @@ jobs:
       # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
       # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
       - name: Build and push Docker image
-        if: (steps.check_tag.outputs.tag_missing == 'true' && inputs.PUSH_IMAGE) || (inputs.FORCE_PUSH_IMAGE)
+        if: (${{ steps.check_tag.outputs.tag_missing == 'true' && inputs.PUSH_IMAGE }}) || (${{ inputs.FORCE_PUSH_IMAGE }})
         # if: inputs.PUSH_IMAGE || inputs.FORCE_PUSH_IMAGE
         uses: docker/build-push-action@v5
         env:
