try out check for tag manually

diff --git a/.github/workflows/build_docker_container.yaml b/.github/workflows/build_docker_container.yaml
--- a/.github/workflows/build_docker_container.yaml
+++ b/.github/workflows/build_docker_container.yaml
@@ -94,20 +94,20 @@ jobs:
             type=raw,value=python${{ inputs.PYVERSION || 3.10 }}-${{ inputs.HASH || hashFiles(inputs.HASHFILES) }}
           labels: |
 
-      # - name: "Check if tag exists"
-      #   uses: tyriis/docker-image-tag-exists@v2.0.0
-      #   id: check_tag
-      #   with:
-      #     # The container image registry
-      #     registry: ${{ env.REGISTRY}}
+      - name: "Check if tag exists"
+        id: check_tag
+        run: |
+          # The container image registry
+          export foo='docker manifest inspect ${{ env.REGISTRY }}/${{ fromJson(steps.meta_slim.outputs.json).images[0] }}/${{ fromJson(steps.meta_slim.outputs.json).tags[0] }}`
       
-      #     # The container image name
-      #     repository: ${{ fromJson(steps.meta_slim.outputs.json).images[0] }}
-      
-      #     # The container image tag
-      #     tag: ${{ fromJson(steps.meta_slim.outputs.json).tags[0] }}
+          if [[ $foo == "" ]]; then
+            echo "tag_missing=true" >> $GITHUB_OUTPUT
+          else
+            echo "tag_missing=true" >> $GITHUB_OUTPUT
+          fi
       - name: Extract metadata (tags, labels) for Docker
         id: meta
+        if: (steps.check_tag.outputs.tag_missing == 'true' && inputs.PUSH_IMAGE) || (inputs.FORCE_PUSH_IMAGE)
         uses: docker/metadata-action@v5
         with:
           images: |
@@ -122,7 +122,7 @@ jobs:
       # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
       # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
       - name: Build and push Docker image
-        if: ( (! docker manifest inspect ${{ env.REGISTRY }}/${{ fromJson(steps.meta_slim.outputs.json).images[0] }}/${{ fromJson(steps.meta_slim.outputs.json).tags[0] }}) && inputs.PUSH_IMAGE) || inputs.FORCE_PUSH_IMAGE
+        if: if: (steps.check_tag.outputs.tag_missing == 'true' && inputs.PUSH_IMAGE) || (inputs.FORCE_PUSH_IMAGE)
         # if: inputs.PUSH_IMAGE || inputs.FORCE_PUSH_IMAGE
         uses: docker/build-push-action@v5
         env:
